theme: jekyll-theme-slate
title: The NOVA System
description: EARLY ALPHA
markdown: kramdown
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "https://the-nova-system.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  posts:
    output: true
    permalink: /posts/:title

plugins:
  - jekyll-feed

kramdown:
  math_engine: katex
feed:
  posts_limit: 50
  excerpt_only: true
