theme: jekyll-theme-cayman
title: The NOVA System
description: a work in progress
author: Garv Shah
markdown: kramdown
baseurl: "/blog"
url: "https://the-nova-system.github.io"
github: [metadata]

social-network-links:
  email: "gshah.6110@gmail.com"
  github: The-NOVA-System

navbar-links:
  Home: "https://the-nova-system.github.io/blog"
  Website: "https://the-nova-system.github.io"

collections:
  posts:
    output: true
    permalink: /posts/:title

plugins:
  - jekyll-feed

kramdown:
  math_engine: katex
feed:
  posts_limit: 50
  excerpt_only: true

pwa:
  sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 15 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/**/*.{js,json,css}"
    - "/**/*.{ico,jpg,jpeg,png,svg}"
    - "/**/*.html"
  precache_glob_ignores: # Optional
    - "sw-register.js"
    - "fonts/**/*"